module sdk.example_structs;

/*
* SDK generated by Dumper-7 for D language
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Example

// Forward declarations
enum class EExampleEnum : ubyte;
struct FExampleStruct;
class UExampleClass;

// Enums
enum EExampleEnum : ubyte
{
    None = 0,
    First = 1,
    Second = 2,
    EExampleEnum_MAX = 3
}

// Structs
struct FVector
{
    float                      X;                                                   // 0x0000(0x0004) Edit, BlueprintVisible, IsPlainOldData, NoDestructor
    float                      Y;                                                   // 0x0004(0x0004) Edit, BlueprintVisible, IsPlainOldData, NoDestructor  
    float                      Z;                                                   // 0x0008(0x0004) Edit, BlueprintVisible, IsPlainOldData, NoDestructor
}

struct FExampleStruct
{
    FVector                    Location;                                            // 0x0000(0x000C) Edit, BlueprintVisible, IsPlainOldData, NoDestructor
    float                      Health;                                              // 0x000C(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    EExampleEnum               ExampleEnum;                                         // 0x0010(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      Pad_11[0x3];                                         // 0x0011(0x0003) Fixing Size After Last Property
}

// Classes  
class UExampleClass // : public UObject
{
public:
    FString                    Name;                                                // 0x0028(0x0010) Edit, BlueprintVisible, ZeroConstructor
    int                        Value;                                               // 0x0038(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      Pad_3C[0x4];                                         // 0x003C(0x0004) Fixing Size After Last Property

public:
    // Functions would go here
    void ExampleFunction(int Param1, float Param2);
    float GetValue() const;
    void SetValue(int NewValue);
}