module sdk.engine_structs;

/*
* SDK generated by Dumper-7 for D language
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Engine

import sdk.basic;
import sdk.unrealcontainers;

// Forward declarations
enum EObjectTypeQuery : ubyte;
enum ECollisionEnabled : ubyte;
struct FHitResult;
struct FVector;
class AActor;
class UPrimitiveComponent;

// Enums
enum EObjectTypeQuery : ubyte
{
    ObjectTypeQuery1 = 0,
    ObjectTypeQuery2 = 1,
    ObjectTypeQuery3 = 2,
    ObjectTypeQuery4 = 3,
    ObjectTypeQuery5 = 4,
    ObjectTypeQuery6 = 5,
    ObjectTypeQuery_MAX = 32
}

enum ECollisionEnabled : ubyte
{
    NoCollision = 0,
    QueryOnly = 1,
    PhysicsOnly = 2,
    QueryAndPhysics = 3,
    ECollisionEnabled_MAX = 4
}

// Structs
struct FHitResult
{
    ubyte                      bBlockingHit : 1;                                    // 0x0000(0x0001) Edit, BlueprintVisible, NoDestructor
    ubyte                      bStartPenetrating : 1;                              // 0x0000(0x0001) Edit, BlueprintVisible, NoDestructor
    ubyte                      BitPad_0_2 : 6;                                     // 0x0000(0x0001) Fixing Bit-Field Size
    ubyte                      Pad_1[0x3];                                         // 0x0001(0x0003) Fixing Size After Last Property
    float                      Time;                                               // 0x0004(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    float                      Distance;                                           // 0x0008(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    FVector                    Location;                                           // 0x000C(0x000C) Edit, BlueprintVisible, IsPlainOldData, NoDestructor
    FVector                    ImpactPoint;                                        // 0x0018(0x000C) Edit, BlueprintVisible, IsPlainOldData, NoDestructor
    FVector                    Normal;                                             // 0x0024(0x000C) Edit, BlueprintVisible, IsPlainOldData, NoDestructor
    FVector                    ImpactNormal;                                       // 0x0030(0x000C) Edit, BlueprintVisible, IsPlainOldData, NoDestructor
    UPrimitiveComponent*       Component;                                          // 0x003C(0x0008) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    AActor*                    Actor;                                              // 0x0044(0x0008) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    FName                      BoneName;                                           // 0x004C(0x0008) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    int                        Item;                                               // 0x0054(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    int                        FaceIndex;                                          // 0x0058(0x0004) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      Pad_5C[0x4];                                        // 0x005C(0x0004) Fixing Size After Last Property
}

struct FCollisionResponseContainer
{
    ubyte                      WorldStatic;                                        // 0x0000(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      WorldDynamic;                                       // 0x0001(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      Pawn;                                               // 0x0002(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      Visibility;                                         // 0x0003(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      Camera;                                             // 0x0004(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      PhysicsBody;                                        // 0x0005(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      Vehicle;                                            // 0x0006(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      Destructible;                                       // 0x0007(0x0001) Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor
}

struct FCollisionProfileData
{
    FName                      Name;                                               // 0x0000(0x0008) Edit, ZeroConstructor, IsPlainOldData, NoDestructor
    ECollisionEnabled          CollisionEnabled;                                  // 0x0008(0x0001) Edit, ZeroConstructor, IsPlainOldData, NoDestructor
    ubyte                      Pad_9[0x3];                                         // 0x0009(0x0003) Fixing Size After Last Property  
    FCollisionResponseContainer ResponseToChannels;                               // 0x000C(0x0008) Edit, NoDestructor
    TArray!(EObjectTypeQuery)  ObjectTypesToQuery;                               // 0x0014(0x0010) Edit, ZeroConstructor
    ubyte                      Pad_24[0x4];                                       // 0x0024(0x0004) Fixing Size After Last Property
}